= Gravitee.io API Management - Gateway

⚠️ DEPRECATED
This repository is no longer active, all the sources have been moved to a new monorepo: link:https://github.com/gravitee-io/gravitee-api-management[Gravitee.io API Management]

The new repository is the single GitHub repository for everything related to Gravitee.io API Management.

== Overview

The gateway is the core component of the Gravitee.io platform. You can compare it to a "smart" proxy to understand its goal.

Unlike traditional HTTP proxy, the gateway is able to apply policies (ie. rules) to both HTTP requests and responses according to your needs, meaning that you can enhance requests and responses processing by adding transformation, security, and many other crazy features!

== Documentation

You can find Gravitee.io API Management documentation from https://docs.gravitee.io/[Gravitee.io website].

== Building

```
$ git clone https://github.com/gravitee-io/gravitee-gateway
$ cd gravitee-gateway
$ mvn clean compile exec:java -Pdev -pl gravitee-gateway-standalone/gravitee-gateway-standalone-container
...
<app starts and listens on port 8082>
```
